### ISSUE TITLE
Non-optional newline in a result

### ISSUE THREAD

**Issue by mallniya** [danpla/ddb_copy_info#1]
Resulting buffer line unconditionally contains newline at the end, which could be unwanted. I propose to make it optional (through config checkbox or special escape sequence in a "Format" line).

**Comment by danpla** [comment]
Do you mean every newline that is implicitly appended to each track info, or only the final one, i.e. the newline that appears at the end of the copied text when you copy information from several tracks?

**Comment by mallniya** [comment]
Since I used this plugin for single track only, I didn't think about multi-track scenario. Though, even for one, I still think that "no new line at the last line" (even if last line is also first) is still valid.
In other words, answering directly to you question -- yes.

**Comment by danpla** [comment]
It's trivial to add such an option, but I wonder whether it makes practical sense. Removing a trailing newline from the pasted text doesn't seem to be a big issue (it's literally a single key press), while changing a plugin setting requires a way more interaction (6 mouse clicks, to be specific: Edit > Preferences > Plugins > Copy info > Newline checkbox > Close).

**Comment by mallniya** [comment]
I understand your point, though it's pretty tedious when working with left hand on WASD and right on mouse to reach Backspace key. Could it be at least optional?

**Comment by mallniya** [comment]
@danpla, finally can use this upgrade, feels nice)
Thank you, much appreciated.

**Comment by danpla** [comment]
You're welcome.
